FROM ubuntu:20.04

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ansible \
    docker.io \
    fakeroot \
    isolinux \
    openssh-server \
    squashfs-tools \
    xorriso

